name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
             # This removes the native credentials which then force tag action to use PAT token instead to be able to generate tags on a protected branch
             persist-credentials: false
             # This is needed to retrieve all commits history in a single branch with 200 being the maximum fetch-depth
             # using fetch-depth "0" gets all commit history for all branches and tags in the repository which we didn't need and felt was an expensive operation
             fetch-depth: "200"
             
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.PAT_ACCESS_NEW }}
       
      - name: Create release
        uses:  ncipollo/release-action@v1
        env : 
          GITHUB_TOKEN: ${{ secrets.PAT_ACCESS_NEW }}
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body : ${{ steps.tag_version.outputs.changelog }}
      
